#!/usr/bin/node

// Import the 'list' array from the '100-data.js' module
const list = require('./100-data.js').list;

// Log the original array
console.log(list);

// Log the new array generated by mapping each element with its index multiplied by the element's value
console.log(list.map((item, index) => item * index));
